<?php
require_once __DIR__ . '/config.php';
$pdo = getDB();
$items = [
  ['hero', 'tagline', 'Where faith meets fades. Crafting confidence through precision cuts for over a decade.'],
  ['hero', 'subtext', 'Be the next pogi in town'],
  ['about', 'title', 'More Than a Haircut.'],
  ['about', 'subtitle', "It's an Experience."],
  ['about', 'text', "At EpiCuts, every snip is intentional, every fade is precise, and every client leaves feeling sharper than they walked in. We blend traditional barbering with modern techniques to give you a cut that speaks confidence."],
  ['about', 'feature1', '3+ Years Experience'],
  ['about', 'feature2', 'Certified Barbers'],
  ['about', 'feature3', 'Premium Products Only'],
  ['about', 'feature4', 'Walk-ins Welcome'],
  ['gallery', 'title', 'Our Work'],
  ['gallery', 'subtitle', 'Every cut tells a story'],
  ['contact', 'title', 'Get in Touch'],
  ['contact', 'subtitle', 'Ready for a fresh cut? Book your appointment or just walk in.'],
  ['contact', 'address', '123 Main Street, Downtown'],
  ['contact', 'phone', '(555) 123-4567'],
  ['contact', 'email', 'hello@epicuts.com'],
  ['general', 'logo', 'EPI'],
  ['general', 'logo_accent', 'CUTS'],
  ['general', 'hours', 'Tue - Sat: 9AM - 7PM | Sun: 10AM - 4PM | Mon: Closed'],
  ['social', 'instagram', '#'],
  ['social', 'facebook', '#'],
  ['social', 'tiktok', '#'],
  ['testimonials', 'section_label', 'Testimonials'],
  ['testimonials', 'title', 'What Our Clients Say'],
  ['testimonials', 'subtitle', 'Real reviews from real people who keep coming back.'],
  ['testimonials', 'card1_text', "Best barber I've ever been to. The skin fade was absolutely flawless. I've been coming here for 3 years and won't go anywhere else."],
  ['testimonials', 'card1_name', 'Marcus T.'],
  ['testimonials', 'card1_role', 'Regular Client'],
  ['testimonials', 'card2_text', 'The attention to detail is unreal. He took his time to get the taper exactly right. Left looking and feeling like a million bucks.'],
  ['testimonials', 'card2_name', 'James R.'],
  ['testimonials', 'card2_role', 'First Timer'],
  ['testimonials', 'card3_text', "Finally found someone who knows how to work with my hair texture. The beard sculpting was on point. My wife couldn't stop complimenting!"],
  ['testimonials', 'card3_name', 'David K.'],
  ['testimonials', 'card3_role', '6+ Years Client'],
  ['testimonials', 'card4_text', 'Clean shop, great music, even better cuts. The hot towel shave is an experience everyone should try at least once. 10/10.'],
  ['testimonials', 'card4_name', 'Alex P.'],
  ['testimonials', 'card4_role', 'Monthly Visitor'],
  ['testimonials', 'card5_text', 'Took my son for his first real haircut and they made him feel comfortable and excited. The result was perfect. Now he asks to go back!'],
  ['testimonials', 'card5_name', 'Sarah L.'],
  ['testimonials', 'card5_role', 'Parent Client'],
  ['testimonials', 'card6_text', 'The textured crop he gave me is the easiest style Ive ever had. Just wash and go. Professional, fast, and exactly what I described.'],
  ['testimonials', 'card6_name', 'Ryan M.'],
  ['testimonials', 'card6_role', 'Weekly Client'],
  ['hero', 'stat_num1', '10+'],
  ['hero', 'stat_label1', 'Years Experience'],
  ['hero', 'stat_num2', '5K+'],
  ['hero', 'stat_label2', 'Happy Clients'],
  ['hero', 'stat_num3', '5.0'],
  ['hero', 'stat_label3', 'Star Rating'],
  ['services', 'section_label', 'What We Offer'],
  ['services', 'title', 'Our Services'],
  ['services', 'subtitle', 'Quality grooming at fair prices. No hidden fees, no surprises.'],
  ['services', 'svc1_name', 'Classic Haircut'],
  ['services', 'svc1_desc', 'Consultation, shampoo, precision cut, and style. The works.'],
  ['services', 'svc1_includes', 'Consultation|Shampoo & Cut|Hot Towel Finish'],
  ['services', 'svc2_name', 'Haircut + Beard'],
  ['services', 'svc2_desc', 'Our signature combo. Full haircut with beard sculpting and lineup.'],
  ['services', 'svc2_includes', 'Everything in Classic|Beard Sculpting|Edge & Line-Up'],
  ['services', 'svc2_badge', 'Most Popular'],
  ['services', 'svc3_name', 'Hot Towel Shave'],
  ['services', 'svc3_desc', 'Old-school straight razor shave. Pure relaxation.'],
  ['services', 'svc3_includes', 'Hot Towel Treatment|Straight Razor Shave|Moisturizer Finish'],
  ['services', 'svc4_name', 'Beard Trim'],
  ['services', 'svc4_desc', 'Shape, sculpt, and detail your beard to perfection.'],
  ['services', 'svc4_includes', 'Beard Shaping|Hot Oil Treatment|Edge Work'],
  ['services', 'dropdown_label', 'Select a Service'],
  ['services', 'dropdown_options', 'Haircut|Haircut + Beard|Hot Towel Shave|Beard Trim|Full Grooming Package'],

];
$stmt = $pdo->prepare("INSERT IGNORE INTO content (section, `key`, value) VALUES (?, ?, ?)");
foreach ($items as $row) $stmt->execute($row);
$pdo->exec("DELETE FROM content WHERE `key` = 'time_slots'");
echo "Migrated: added " . count($items) . " content fields.<br>";
echo 'Now <a href="/api/admin/content.php">go to admin Content</a> to edit them.';
